### ISSUE TITLE
"no module named 'traceback'" exception on Matrix Portal M4

### ISSUE THREAD

**Issue by tammymakesthings** [adafruit/Adafruit_CircuitPython_asyncio#23]
I'm getting an exception trying to import asyncio on my device. I've stripped this down to a minimal test case, which is as follows:

Device: Adafruit Matrix Portal M4, running CircuitPython 7.3.1
I wiped the `lib` directory clean on my device and then installed a bare minimum subset of libraries with the command:
```
circup install adafruit_matrixportal asyncio
```
I loaded a minimal `code.py` file onto the device as follows:
```python
import asyncio

print("Hello from asyncio on the MatrixPortal!")
while True:
    pass
```
When the device restarts, the following is logged in the serial console:
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 1, in <module>
  File "asyncio/__init__.py", line 14, in <module>
  File "asyncio/core.py", line 19, in <module>
ImportError: no module named 'traceback'

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```
I'm happy to dive deeper into this issue and see if I can figure out what's going on, but I probably won't have time for at least a few days. I haven't tested whether this problem occurs on other boards/platforms yet, or whether it goes away if I down-rev CircuitPython, but I will do those tests and update the issue as soon as I have a bit of time.

**Comment by ladyada** [comment]
hmm what if you try the 'absolute latest' firmware?

**Comment by dhalbert** [comment]
This is a mistake I made, trying to get the builds to fit. I'll correct it and point you to a fixed build.
